name: nusa_learn
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  cupertino_icons: ^1.0.2
  firebase_core: ^2.24.2
  firebase_core_web: ^2.10.0
  firebase_auth: ^4.15.3
  firebase_auth_web: ^5.8.12
  cloud_firestore: ^4.13.6
  cloud_firestore_web: ^3.8.10
  uuid: ^4.3.3
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.4
  fake_cloud_firestore: ^2.4.8
  firebase_auth_mocks: ^0.13.0
  test: ^1.24.9
  build_runner: ^2.4.8

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/fonts/

  fonts:
    - family: Jomhuria
      fonts:
        - asset: assets/fonts/Jomhuria-Regular.ttf
